### ISSUE TITLE
Install failed `error: failed to compile `

### ISSUE THREAD

**Issue by s41n1k** [iustin24/chameleon#3]
Hi,
In my ubuntu VPS, my installation failed. The below error msg given
```
error: failed to compile `chameleon v1.0.0 (https://github.com/iustin24/chameleon#3836b280)`, intermediate artifacts can be found at `/tmp/cargo-installpD993V`
``` 
Any suggestion for this?
Thank you

**Comment by iustin24** [comment]
HI @s41n1k,

Can you post the full error you are getting? There should be additional information as to why it failed.

**Comment by Raeein** [comment]
This did it for me @s41n1k: `sudo apt-get install -y pkg-config`


@iustin24 Im trying to install chameleon but it keeps getting stuck on building headless_chrome. Any idea? 64-bit ubuntu VPS.


![Screen Shot 2022-09-11 at 5 20 33 PM](https://user-images.githubusercontent.com/78040718/189549327-3b01c857-e7a0-4ecf-8746-7b4e078ddbd5.png)

**Comment by iustin24** [comment]
Hi @Raeein,

How much RAM does your VPS have? 
I noticed the compiler hangs on `headless_chrome` when I tested it on a 1GB VPS.

**Comment by iustin24** [comment]
Also, @s41n1k

As @Raeein mentioned, you are most likely missing a dependency. It's hard to tell which one you are missing unless I can see the full error.

You can install all the dependencies required on ubuntu like so:
```
apt install libssl-dev build-essential pkg-config
```

**Comment by Raeein** [comment]
This is the error I got after an hour. I have 2g of ram and it had 80% utilization when I was running the script.


<img width="1405" alt="Screen Shot 2022-09-11 at 7 22 50 PM" src="https://user-images.githubusercontent.com/78040718/189553360-419be1c9-55c9-4a7d-b8b9-62ba18ed8d63.png">

`error: could not compile
headless chrome'
Caused by:
process didn't exit successfully:
rustc
-crate-name headless chrome
-edition=2018 /home/ryan/.cargo/git/checkouts/rust-headless-chrome-2b5d819bbb1966eb/1
011082/src/lib.rs--error-format=ison--json=diagnostic-rendered-ansi,artifacts,future-incompat--crate-typelib--emit=dep-info,metadata,link-Copt-level=3
-C embed-bitcode=no --cfg 'feature="default"' - -cfg
"feature="directories"' --cfg
"feature="fetch"' --cfg 'feature="ureg" '
--cfa
"feature="walkdir"
_-cfg
•fe
ature="zip"'
-C metadata=b14d4434alc872f6
-C extra-filename=-b14d4434alc872f6--out-dir/tmp/cargo-installB8Zj95/release/deps-Ldependency=/tmp/cargo-install
B8Zj95/release/deps--externanyhow=/tmp/cargo-installB8Zj95/release/deps/libanyhow-8a03d4784b600546.rmeta--externbase64=/tmp/cargo-installB8Zj95/release/de
ps/libbase64-ffc6a74fe66f9f4f.rmeta
-extern derive builder=/tmp/cargo-installB8Zj95/release/deps/libderive builder-54a090d49e9ad7ce.so
-extern directories=/
tmp/cargo-installB8Zj95/release/deps/libdirectories-94da0c600bf6flac.rmeta--externlog=/tmp/cargo-installB8Zj95/release/deps/liblog-d4c6cdec49ace013.rmeta
externrand=/tmp/cargo-installB8Zi95/release/deps/librand-6d2a92cc833f0892.rmeta--externregex=/tmp/cargo-installB&Zi95/release/deps/libregex-75f682446759539
f.rmeta--externserde=/tmp/cargo-installB8Zi95/release/deps/libserde-8275fbf51015b98.rmeta--externserdeison=/tmp/cargo-installB8Zi95/release/deps/libserd
eison-a3722fc23775ca34. rmeta
--externtempfile=/tmp/cargo-installB8Zi95/release/deps/libtempfile-fobdldc47a4d13a0.rmeta--externthiserror=/tmp/cargo-install
B8Zj95/release/deps/libthiserror-d&e3d0f31c620ae5.rmeta--externureq=/tmp/cargo-installB8Zj95/release/deps/libureq-1f920c45abb8bf07.rmeta--externwalkdir=/t
mp/cargo-installB8Zi95/release/deps/libwalkdir-8945e4ad33de6748.rmeta--externwebsocket=/tmp/cargo-installB8Zi95/release/deps/libwebsocket-8bad7al6ae72a291.r
meta
--externwhich=/tmp/cargo-installB8Zj95/release/deps/libwhich-a5f4d9le283d532c.rmeta
--externzip=/tmp/cargo-installB8Zi95/release/deps/libzip-1f79749669
894528.meta --cap-lints allow -L native=/tmp/cargo-installB8Zj95/release/build/ring-7b5aeb3b1655d8b5/out
-L native=/tmp/cargo-installB8Zj95/release/build/bzi
p2-sys-d2845210a9a35559/out/lib
(signal:
9, SIGKILL: kill
error: failed to compile
chameleon v1.0.0 (https://qithub.com/iustin24/chameleon#b14d6b03)'
intermediate artifacts can be found at
/tmp/cargo-installB8Zi95`

**Comment by iustin24** [comment]
Can you run this command and see if there's any output?
`dmesg | egrep -i 'killed process'`

**Comment by Raeein** [comment]
Yes, this is the output: 
`[3276182.741065] Out of memory: Killed process 2226297 (rustc) total-vm:2049600kB, anon-rss:1338724kB, file-rss:0kB, shmem-rss:0kB, UID:1000 pgtables:3748kB oom_score_adj:0
`

**Comment by iustin24** [comment]
Yeah, it looks like you are running out of memory while compiling.

**Comment by Raeein** [comment]
Probably yea it did build on my own computer. Thanks for the help!!

**Comment by s41n1k** [comment]
[This is to fix the problem](https://github.com/iustin24/chameleon/issues/3#issuecomment-1243062611). Thanks

**Comment by iustin24** [comment]
Hi @Raeein,

You can now use the install script to download binary. This should work on your VPS too, since it will no longer require compiling the tool.

**Comment by Raeein** [comment]
Hi @iustin24,

Much appreciated it works like a charm now. I have to throttle it down significantly because I keep getting banned haha!
